### ISSUE TITLE
add a search bar

### ISSUE THREAD

**Issue by nikitavoloboev** [nikitavoloboev/knowledge-map-search-engine#1]
And style it. [DuckDuckGo](https://duckduckgo.com/)'s one is really nice, can probably copy it.

**Comment by flexbox** [comment]
Maybe you can use https://community.algolia.com/instantsearch.js/ for that ?

**Comment by nikitavoloboev** [comment]
This seems really great indeed. Thank you a lot for the link. In my case the initial search engine should be fairly simple. User types query, iframe with mind map pops up. I will try to see if I can implement it.

Want to help? :)

**Comment by flexbox** [comment]
If you can extract your data in a `.json` file I think it's possible.

The other solution is to scrape the web site but it's impossible with a DOM like that -_-
<img width="798" alt="capture d ecran 2017-05-04 a 16 20 01" src="https://cloud.githubusercontent.com/assets/360936/25708024/9080c1b0-30e5-11e7-99fb-2c8b2999265e.png">
